backend:
  name: github
  repo: nguyenhero/loki_nieu
site_url: https://nguyenloki.com
display_url: https://nguyenloki.com
logo_url: https://your-site.com/images/logo.png
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets
collections:
  - name: settings
    label: Cấu hình
    delete: false
    editor:
      preview: false
    files:
      - name: config
        label: Cấu hình chung
        file: _data/site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Tiêu đề trang
            required: true
            hint: ""
            default: ""
          - widget: string
            name: siteUrl
            label: Đường dẫn website
            required: true
            hint: ""
            default: ""
          - widget: text
            name: description
            label: Mô tả
            default: ""
            required: false
            hint: ""
          - widget: object
            name: home
            label: Trang chủ
            fields:
              - widget: string
                name: title
                label: Giới thiệu
                default: ""
                required: false
                hint: ""
              - widget: markdown
                name: description
                label: Nội dung
                default: ""
                required: false
                hint: ""
                buttons: []
            required: true
            hint: ""
          - label: Trang hôn lễ
            name: wedding
            required: true
            widget: object
            hint: ""
            fields:
              - label: Album Json
                name: albumJson
                required: true
                widget: string
                hint: ""
                default: ""
              - label: Album
                name: ablum
                required: true
                widget: list
                hint: ""
                default: ""
                allow_add: true
                field: ""
                fields: ""
  - name: blog
    label: Bài viết
    folder: _data/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Mẫu bài viết
        name: template
        required: true
        widget: hidden
        hint: ""
        default: BlogPost
      - label: Đường dẫn
        name: path
        required: true
        widget: string
        hint: Đường dẫn phải bắt đầu bằng /
        default: ""
      - label: Ngày tạo
        name: date
        required: true
        widget: datetime
        hint: ""
        default: ""
        format: ""
        dateFormat: ""
        timeFormat: ""
      - label: Tiêu đề
        name: title
        required: true
        widget: string
        hint: ""
        default: Tiêu đề bài viết
      - label: Tóm tắt
        name: metaDescription
        required: true
        widget: text
        hint: ""
        default: ""
      - label: Ảnh đại diện
        name: thumbnail
        required: true
        widget: image
        hint: Kích thước khuyến nghị 1280x800
        default: ""
        allow_multiple: false
      - label: Cấu hình
        name: config
        required: true
        widget: object
        hint: ""
        fields:
          - label: Bài viết liên quan
            name: relationBlog
            required: true
            widget: relation
            hint: Chọn bài viết liên quan
            default: ""
            collection: blog
            displayFields: "['title', 'metaDescription']"
            searchFields: "['title', 'body']"
            valueField: "['title', 'body','metaDescription','thumbnail']"
            multiple: true
            optionsLength: 20
          - label: File tải về
            name: files
            required: false
            widget: file
            hint: ""
            default: ""
            allow_multiple: true
      - label: Nội dung
        name: body
        required: true
        widget: markdown
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - heading-five
          - heading-six
          - code
          - link
          - quote
          - heading-one
          - code-block
          - bulleted-list
          - heading-two
          - heading-three
          - numbered-list
          - heading-four
    identifier_field: ""