backend:
  name: github
  repo: nguyenhero/loki_nieu
site_url: https://nguyenloki.com
display_url: https://nguyenloki.com
logo_url: https://your-site.com/images/logo.png
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets
collections:
  - name: settings
    label: Settings
    delete: false
    editor:
      preview: false
    files:
      - name: config
        label: Site Setting
        file: _data/site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: ""
            default: ""
          - widget: string
            name: siteUrl
            label: Website url
            required: true
            hint: ""
            default: ""
          - widget: text
            name: description
            label: Description
            default: ""
            required: false
            hint: ""
          - widget: object
            name: home
            label: Home Page
            fields:
              - widget: string
                name: title
                label: Title
                default: ""
                required: false
                hint: ""
              - widget: markdown
                name: description
                label: Description
                default: ""
                required: false
                hint: ""
                buttons: []
            required: true
            hint: ""
          - label: Wedding Page
            name: wedding
            required: true
            widget: object
            hint: ""
            fields:
              - label: Album Json
                name: albumJson
                required: true
                widget: string
                hint: ""
                default: ""
              - label: Album
                name: ablum
                required: true
                widget: list
                hint: ""
                default: ""
                allow_add: true
                field: ""
                fields: ""
  - name: blog
    label: Blog
    folder: _data/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Template
        name: template
        required: true
        widget: hidden
        hint: ""
        default: BlogPost
      - label: Path
        name: path
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Date
        name: date
        required: true
        widget: datetime
        hint: ""
        default: ""
        format: ""
        dateFormat: ""
        timeFormat: ""
      - label: Title
        name: title
        required: true
        widget: string
        hint: ""
        default: ""
      - label: Sapo
        name: metaDescription
        required: true
        widget: text
        hint: ""
        default: ""
      - label: Thumbnail
        name: thumbnail
        required: true
        widget: image
        hint: ""
        default: ""
        allow_multiple: false
      - label: Config
        name: config
        required: true
        widget: object
        hint: ""
        fields:
          - label: Relation Blog
            name: relationBlog
            required: true
            widget: relation
            hint: ""
            default: ""
            collection: blog
            displayFields: "['title', 'metaDescription']"
            searchFields: "['title', 'body']"
            valueField: "['title', 'body','metaDescription','thumbnail']"
            multiple: true
            optionsLength: 20
          - label: File Download
            name: files
            required: false
            widget: file
            hint: ""
            default: ""
            allow_multiple: true
      - label: Body
        name: body
        required: true
        widget: markdown
        hint: ""
        default: ""
        buttons:
          - bold
          - italic
          - heading-five
          - heading-six
          - code
          - link
          - quote
          - heading-one
          - code-block
          - bulleted-list
          - heading-two
          - heading-three
          - numbered-list
          - heading-four
    identifier_field: ""